---
- name: Kibana
  hosts: kibana
  become: yes

  tasks:
  
  - name: Repo
    get_url:
      url: 'https://mirror.yandex.ru/mirrors/elastic/7/pool/main/k/kibana/kibana-7.17.9-amd64.deb'
      dest: '/home/popov/kibana-7.17.9-amd64.deb'

  - name: Dpkg Kibana
    apt:
      deb: '/home/popov/kibana-7.17.9-amd64.deb'
      
  - name: Update 
    apt:
      update_cache: yes

  - name: Daemon reload
    systemd:
      daemon_reload: true
      name: kibana.service
      state: started

  - name: Conf file
    copy:
      src: /home/popov/ansible/kibana.yml
      dest: /etc/kibana/kibana.yml
      owner: root
      group: kibana

  - name: Restart Kibana
    systemd:
      name: kibana.service
      state: restarted
