---
- name: Filebeat
  hosts: all
  become: yes

  tasks:
  
  - name: Repo
    get_url:
      url: 'https://mirror.yandex.ru/mirrors/elastic/7/pool/main/f/filebeat/filebeat-7.17.9-amd64.deb'
      dest: '/home/popov/filebeat-7.17.9-amd64.deb'

  - name: Dpkg Filebeat
    apt:
      deb: '/home/popov/filebeat-7.17.9-amd64.deb'
      
  - name: Update 
    apt:
      update_cache: yes    

  - name: Daemon reload
    systemd:
      daemon_reload: true
      name: filebeat.service
      state: started

  - name: Conf-file
    copy:
      src: /home/popov/ansible/filebeat.yml
      dest: /etc/filebeat/filebeat.yml
      owner: root
      group: root

  - name: Restart filebeat
    systemd:
      name: filebeat.service
      state: restarted