---
- name: DB-command
  hosts: zabbix-server
  become: yes

  tasks:
      
  - name: Character
    shell: 
      chdir: /home/popov/db 
      cmd: sudo docker-compose exec -it db_mysql_1 mysql -uroot -p--- | create database zabbix character set utf8mb4 collate utf8mb4_bin;  

  - name: Privileges
    shell: 
      chdir: /home/popov/db 
      cmd: sudo docker-compose exec -it db_mysql_1 mysql -uroot -p--- | grant all privileges on zabbix.* to zabbix@localhost; 
      
  - name: Global trust
    shell: 
      chdir: /home/popov/db 
      cmd: sudo docker-compose exec -it db_mysql_1 mysql -uroot -p--- | set global log_bin_trust_function_creators = 1;
          
  - name: DBzabbix
    shell: 
      chdir: /home/popov/db    
      cmd: sudo docker-compose exec -it db_mysql_1 mysql -uroot -p--- | --default-character-set=utf8mb4 -uzabbix -p 12345678
      
  - name: Global trust2
    shell: 
      chdir: /home/popov/db 
      cmd: sudo docker-compose exec -it db_mysql_1 mysql -uroot -p--- | set global log_bin_trust_function_creators = 0;   
   
  - name: Restart
    shell: sudo systemctl restart zabbix-server zabbix-agent apache2 | sudo systemctl enable zabbix-server zabbix-agent apache2
