 version: "3"
 services:
   mysql:
     image: mariadb:10.6.4-focal
     volumes:
       - db_data:/var/lib/mysql
     network_mode: host
     environment:
       - MYSQL_ROOT_PASSWORD=---
       - MYSQL_DATABASE=zabbix 
       - MYSQL_USER=zabbix 
       - MYSQL_PASSWORD=---
       - MYSQL_ROOT_HOST="%"
       
 volumes:
   db_data: {}
