 version: "3"
 services:
   pgsql:
     image: postgres:14-bullseye
     network_mode: host
     volumes:
       - db_data:/var/lib/pgsql
     environment:
       - POSTGRES_ROOT_PASSWORD=12345678
       - POSTGRES_DATABASE=zabbix
       - POSTGRES_USER=zabbix
       - POSTGRES_PASSWORD=12345678
       - POSTGRES_ROOT_HOST="%"
   zabbix-server:
     image: zabbix/zabbix-server-pgsql:ubuntu-6.0-latest
     network_mode: host
     environment:
       - DB_SERVER_HOST=localhost
       - POSTGRES_DATABASE=zabbix
       - POSTGRES_USER=zabbix 
       - POSTGRES_PASSWORD=12345678
     depends_on: 
       - pgsql
   zabbix-web:
     image: zabbix/zabbix-web-apache-pgsql:ubuntu-6.0-latest
     network_mode: host
     environment:
       - DB_SERVER_HOST=localhost
       - POSTGRES_DATABASE=zabbix
       - POSTGRES_USER=zabbix 
       - POSTGRES_PASSWORD=12345678 
     depends_on: 
       - zabbix-server
       - pgsql
 volumes:
   db_data: {}
