[nginx]
nginx-1 ansible_host=nginx-1.ru-central1.internal
nginx-2 ansible_host=nginx-2.ru-central1.internal

[zabbix-server]
zabbix-server ansible_host=zabbix.ru-central1.internal

[elastic]
elasticsearch ansible_host=elasticsearch.ru-central1.internal

[kibana]
kibana ansible_host=kibana.ru-central1.internal

[filebeat]
nginx-1 ansible_host=nginx-1.ru-central1.internal
nginx-2 ansible_host=nginx-2.ru-central1.internal

[all:vars]
ansible_ssh_user=popov
ansible_ssh_private_key_file=/home/popov/.ssh/id_rsa